apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 1m
  chart:
    spec:
      chart: jenkins
      version: '3.4.0'
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      interval: 1m
  values:
