apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: hpa-example
spec:
  interval: 1m
  chart:
    spec:
      chart: ./hpa-example
      sourceRef:
        kind: GitRepository
        name: charts
        namespace: flux-system
      interval: 1m
  values:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 50