apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  interval: 1m
  chart:
    spec:
      chart: elasticsearch
      version: '7.13.2'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 1m
  values:
    replicas: 1
    minimumMasterNodes: 1
    resources:
      requests:
        cpu: "100m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"    