apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: elastic
spec:
  interval: 1m
  chart:
    spec:
      chart: filebeat
      version: '7.13.2'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 1m
  values:
