apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  interval: 1m
  chart:
    spec:
      chart: tekton
      # version: '0.25.0'
      sourceRef:
        kind: HelmRepository
        name: jenkins-x
        namespace: flux-system
      interval: 1m
  values:
