apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://github.com/miccioest/charts.git
  ref:
    branch: main
  secretRef:
    name: flux-system