apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/miccioest/charts
  ref:
    branch: main


# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: GitRepository
# metadata:
#   name: flux-system
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   ref:
#     branch: main
#   secretRef:
#     name: flux-system
#   url: ssh://git@github.com/miccioest/gitops-demo.git