apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wp
  namespace: wp
spec:
  interval: 1m
  chart:
    spec:
      chart: wordpress
      version: '11.0.16'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values: